ShareHouseTheatre/Models/ContactModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShareHouseTheatre.Models
{
	public class ContactModel {
		public string Name { get; set; }
		public string Email { get; set; }
		public string Website { get; set; }
		public string Message { get; set; }
		public string Required { get; set; }
		public string RequiredToPost { get; set; }
		public string T { get; set; }
	}
}

ShareHouseTheatre/Controllers/ContactSurfaceController.cs
using System;
using System.Text;
using System.Web.Mvc;
using umbraco;
using Umbraco.Core.Logging;
using Umbraco.Web.Mvc;
using ShareHouseTheatre.Models;
using System.Text.RegularExpressions;

namespace ShareHouseTheatre.Controllers
{
	public class ContactSurfaceController : SurfaceController
	{

		[HttpPost]
		public ActionResult Contact(ContactModel model)
		{

			ActionResult actionResult;

			//Check for honeypot entry
			if(!String.IsNullOrEmpty(model.Required) || !String.IsNullOrEmpty(model.RequiredToPost)){
				actionResult = base.PartialView("contact/ContactFormSuccess"); //thanks, your spam has been disregarded!
			} else {

				//check for empty required fields
				if(!base.ModelState.IsValid || String.IsNullOrEmpty(model.Name) || String.IsNullOrEmpty(model.Message) || String.IsNullOrEmpty(model.Email) ){
					if(String.IsNullOrEmpty(model.Name)){
						ViewBag.error = "Name cannot be empty";
					} else if (String.IsNullOrEmpty(model.Email)){
						ViewBag.error = "Email cannot be empty";
					} else if (String.IsNullOrEmpty(model.Message)){
						ViewBag.error = "Message cannot be empty";
					} else if (String.IsNullOrEmpty(model.T)){
						ViewBag.error = "Ensure all fields are filled out";
					} else if(!base.ModelState.IsValid){
						ViewBag.error = "Ensure all fields are filled out";
					}
					return base.PartialView("Contact/ContactFormError");
				}

				//Check if the message contains any urls
				//Do this after null checking model.Message
				if(checkForUrls(model.Message)){
					return base.PartialView("contact/ContactFormSuccess"); //thanks, your spam has been disregarded!
				}


				//Do some simple decryption
				//Do this after null checking model.T
				if(decyrptIsValid(model.T) == false) {
					return base.PartialView("contact/ContactFormSuccess"); //thanks, your spam has been disregarded!
				}


				string to = "sharehousetheatreco@gmail.com";
				//string to = "matt@milkmanmatty.com";
				string from = "mailbot@milkmanmatty.com";

				var sb = new StringBuilder();
				sb.AppendFormat("<p>Name: {0}</p>", model.Name);
				sb.AppendFormat("<p>Email: {0}</p>", model.Email);
				if(!String.IsNullOrEmpty(model.Website)){
					sb.AppendFormat("<p>Website: {0}</p>", model.Website);
				}
				sb.AppendFormat("<p>Message: {0}</p>", model.Message);

				try {
					library.SendMail(from, to, "New website enquiry!", sb.ToString(), true);
					actionResult = base.PartialView("Contact/ContactFormSuccess");
				}
				catch (Exception ex) {
					LogHelper.Error(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType, "msg", ex);
					actionResult = base.PartialView("Contact/ContactFormError");
				}
			}
			return actionResult;
		}

		private bool checkForUrls(string msg) {
			Regex rgx = new Regex(@"((http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&amp;:/~\+#]*[\w\-\@?^=%&amp;/~\+#])?)");
			return rgx.IsMatch(msg);
		}


		private bool decyrptIsValid(string timestamp) {

			var _base = timestamp.ToCharArray();
			char[] salt = "Milkman Matty".ToCharArray();
			char[] dencrypted = new char[_base.Length];
			for(int i = 0; i < _base.Length; i++) {
				dencrypted[i] = (char) ( _base[i] - salt[i%salt.Length] );
			}

			// something like "20180225121840"
			string de_string = new string(dencrypted);
			
			string cur_time = DateTime.Now.ToString("yyyyMMddHHmmss");

			if(long.Parse(de_string)+4 > long.Parse(cur_time)) {
				return false;
			}
			return true;
		}
	}
}

ShareHouseTheatre/Views/Events.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "PageMaster.cshtml";
}

@section headScripts {
	<link href="/css/style.css" rel="stylesheet">
}

<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h1 class="center">Events</h1>
			<div class="event_blurb center">
				@Model.Content.GetPropertyValue("blurb")
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<div id="calendar"></div>

			<script type="text/template" id="full-clndr-template">
				<div class="clndr-controls">
					<div class="clndr-previous-button">&lt;</div>
					<div class="clndr-next-button">&gt;</div>
					<div class="current-month"><%= month %> <%= year %></div>
				</div>
				<div class="clndr-grid">
					<div class="days-of-the-week clearfix">
						<% _.each(daysOfTheWeek, function(day) { %>
							<div class="header-day"><%= day %></div>
						<% }); %>
					</div>
					<div class="days">
						<% _.each(days, function(day) { %>
							<div class="<%= day.classes %>" id="<%= day.id %>"><span class="day-number"><%= day.day %></span></div>
						<% }); %>
					</div>
				</div>
				<div class="event-listing">
					<div class="event-listing-title">Events This Month</div>
					<% _.each(eventsThisMonth, function(event) { %>
					<div class="event-item">
						<div class="event-item-name"><%= event.title %>: 
							<% if(event.startmo == event.endmo){ %>
								<% if(event.startday == event.endday){ %>
									<%= event.start.split('-')[2] %> <%= event.startmo %>
								<% } else { %>
									<%= event.start.split('-')[2] %> - <%= event.end.split('-')[2] %> <%= event.startmo %>
								<% } %>
							<% } %>
							<% if(event.startmo != event.endmo){ %>
								<%= event.start.split('-')[2] %> <%= event.startmo %> - <%= event.end.split('-')[2] %> <%= event.endmo %>
							<% } %>
							</div>
						<div class="event-item-location">@@ <%= event.location %></div>
						<div class="event-item-details"><%= event.details %></div>
						<% if( new Date(event.end) >= new Date() ){ %>
						<div class="event-item-url"><a href="<%= event.tickets %>">Buy Tickets</a></div>
						<% } %>
					</div>
					<% }); %>
				</div>
			</script>

		</div>
	</div>
</div>

@section scripts {
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/en-au.js"></script> -->
	<script src="~/js/underscore-min.js"></script>
	<script src="~/js/cldr.min.js"></script>
	<script>
	@{ var events = Umbraco.TypedContent(1062).Children(); }
	var Events = [
	@foreach(var e in events) {
		string startD = e.GetPropertyValue<DateTime>("eventStartDate").ToString("yyyy-MM-dd");
		string startDay = e.GetPropertyValue<DateTime>("eventStartDate").ToString("dd");
		string startMo = e.GetPropertyValue<DateTime>("eventStartDate").ToString("MMMM");

		string endD = e.GetPropertyValue<DateTime>("eventFinishDate").ToString("yyyy-MM-dd");
		string endDay = e.GetPropertyValue<DateTime>("eventFinishDate").ToString("dd");
		string endMo = e.GetPropertyValue<DateTime>("eventFinishDate").ToString("MMMM");

		string output = "date: '" + startD + "', "+
						"start: '" + startD + "', " +
						"startday: '" + startDay + "', " +
						"startmo: '" + startMo + "', " +
						"end: '" + endD + "', " +
						"endday: '" + endDay + "', " +
						"endmo: '" + endMo + "', " +
						"title: '" + e.GetPropertyValue<string>("title") + "', " +
						"details: \"" + e.GetPropertyValue<string>("summary").Replace("\"","\\\"").Replace("\r", "").Replace("\n", "") + "\", " +
						"location: '" + e.GetPropertyValue<string>("location") + "', " +
						"eventURL: '" + e.Url() + "', " +
						"tickets: '" + e.GetPropertyValue<string>("ticketURL") + "'";
		@Html.Raw("{ " + output + " },\r\n")
	}
	];
	$('#calendar').clndr({
		template: $('#full-clndr-template').html(),
		events: Events,
		dateParameter: 'end',
		multiDayEvents: {
				endDate: 'end',
			startDate: 'start'
		},
		clickEvents: {
			click: function (target) {
				window.location = target.events[0].eventURL;
			}
		},
		daysOfTheWeek: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
		forceSixRows: true
	});
	</script>
}

ShareHouseTheatre/Views/Gallery.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "PageMaster.cshtml";
}
@section headScripts {
	<link href="/css/style.css" rel="stylesheet">
}

<div class="container">
	<div class="row">
	@foreach(var gallery in Model.Content.Children()){
		var gImgs = gallery.GetPropertyValue<IEnumerable<IPublishedContent>>("galleryPhotos");
		var first = gImgs.First();
		<div class="col-12 col-md-6">
			<div class="gallery_child">
				<a href="@gallery.Url()">
				@if(first != null){
					<img src="@first.Url()"  class="img-responsive" alt="" />
				}
					<h2 class="gallery_heading" href="@gallery.Url()">@gallery.GetPropertyValue("galleryHeading")</h2>
				</a>
			</div>
		</div>
	}
	</div>
</div>

ShareHouseTheatre/Views/GalleryShowcase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "PageMaster.cshtml";
}
@section headScripts {
	<link href="/css/style.css" rel="stylesheet">
}

<div class="container">
	<div class="row">
		<div class="col-xs-12 mb20">
			<h2 class="gallery_heading">@Model.Content.GetPropertyValue("galleryHeading")</h2>
			@Model.Content.GetPropertyValue("galleryBlurb")
		</div>
	</div>
@for(int i = 0; i < Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("galleryPhotos").Count(); i++) {
	var img = Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("galleryPhotos").ElementAt(i);
	if(i % 4 == 0){ @Html.Raw("<div class='row'>") }
			<div class="col-xs-12 col-sm-3">
				<div class="gallery_child">
				@if(img != null) {
					<a href="@img.Url()" target="_blank">
						<img src="@img.Url()" class="img-responsive" alt="" />
					</a>
				}
				</div>
			</div>
	if(i % 4 == 3 || i == Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("galleryPhotos").Count()-1) { @Html.Raw("</div>") }
}
</div>

ShareHouseTheatre/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "PageMaster.cshtml";

	string bgimg = Model.Content.GetPropertyValue<IPublishedContent>("bgimg") != null ? Model.Content.GetPropertyValue<IPublishedContent>("bgimg").Url() : "../img/sharehouselogo_large.jpg";
}
@section headScripts {
	<link href="/css/style.css" rel="stylesheet">
}

<div class="main-banner" style="background-image: url(@bgimg);">
	<div class="block-centered">
		@if(Model.Content.GetPropertyValue<bool>("showBannerContent")) {
		<div class="user-content">@Model.Content.GetPropertyValue("bannerText")</div>
		<a href="@Model.Content.GetPropertyValue("buttonUrl")" class="round-btn">Buy Tickets</a>
		}
	</div>
</div>

<!-- Main Content -->
<div class="main home">
	<div class="container">
		<!-- Upcoming events -->
		<div class="upcoming_events">
			<h4>at the theatre</h4>
			<h2>@Model.Content.GetPropertyValue("eventsHeading")</h2>
			<div class="line"></div>

			<div class="row show_container">
				@{
					var events = Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("eventsToShow");
				}
				@foreach(var ev in events) {
				<div class="col-xs-12 col-sm-6 col-md-4 show_card">
					<a href="@ev.Url()">
						@{
							var eventImg = ev.GetPropertyValue<IPublishedContent>("bannerImage") == null ? "" : ev.GetPropertyValue<IPublishedContent>("bannerImage").Url();
						}
						<img src="@eventImg" alt="" class="img-responsive" />
					</a>
					<div class="event-content">
						<div class="bottom_aligner"></div>
						<div class="content">
							<h3 class="entry-title summary">
								<a href="@ev.Url()">@ev.GetPropertyValue("title")</a>
							</h3>
							@{
								DateTime today = DateTime.Now;
								string day = "";
								string date = "";
								if(today > ev.GetPropertyValue<DateTime>("eventStartDate") &&
									today < ev.GetPropertyValue<DateTime>("eventFinishDate"))
								{
									day = ev.GetPropertyValue<DateTime>("eventStartDate").ToString("dddd");
									date = ev.GetPropertyValue<DateTime>("eventStartDate").ToString("dd MMMM");
								}
								else if(today < ev.GetPropertyValue<DateTime>("eventStartDate")) {
									day = "Starts " + ev.GetPropertyValue<DateTime>("eventStartDate").ToString("dddd");
									date = ev.GetPropertyValue<DateTime>("eventStartDate").ToString("dd MMMM");
								}
								else if(today > ev.GetPropertyValue<DateTime>("eventFinishDate")) {
									day = "Ended " + ev.GetPropertyValue<DateTime>("eventFinishDate").ToString("dddd");
									date = ev.GetPropertyValue<DateTime>("eventFinishDate").ToString("dd MMMM");
								}


							}
							<div class="event-time-container">
								<div class="event-weekday">@day</div>
								<div class="event-date">@date</div>
							</div>
							<div class="event-link">
								<a class="round-btn" href="@ev.Url()"><span class="text">More Info</span></a>
							</div>
						</div>
					</div>
				</div>
				}
			</div>
		</div>
	</div>

	<!-- INSET -->
	<div class="row no_marg inset">
		<div class="col-xs-12 col-md-6"></div>
		<div class="col-xs-12 col-md-6 no_pad">
			<div class="background">
				<img src="~/img/traces2.jpg" alt="" class="img-responsive" />
			</div>
			<div class="content">
				<h3>@Model.Content.GetPropertyValue("inset")</h3>
			</div>
		</div>
	</div>

	<!-- ABOUT INSET -->
	<div class="container inset_about">
		<div class="background">
			<div class="content">
				<h4>about us</h4>
				<h2>@Model.Content.GetPropertyValue("aboutUsHeading")</h2>
				<div class="line"></div>
				<div class="user_content">
					@Model.Content.GetPropertyValue("aboutUsBlurb")
				</div>
			</div>
		</div>
	</div>

	<!-- MASK / TEAM -->
	<div class="container mask_team">
		<div class="row">
			<div class="col-xs-12 col-md-6 mask">
				@{ string mask = Model.Content.GetPropertyValue<IPublishedContent>("mask") != null ? Model.Content.GetPropertyValue<IPublishedContent>("mask").Url() : "~/img/mask_hoz.png"; }
				<img src="@mask" alt="" class="img-responsive" />
			</div>
			<div class="col-xs-12 col-md-6 team">
				<div class="content">
					<h4>our staff</h4>
					<h2>@Model.Content.GetPropertyValue("ourStaffHeading")</h2>
					<div class="line"></div>
					<div class="user_content">
						@Model.Content.GetPropertyValue("ourStaffBlurb")
					</div>
					<div class="team_link">
						<a class="round-btn" href="/team/"><span class="text">View All Team</span></a>
					</div>
				</div>
			</div>
		</div>

		<!-- Team Members -->
		<div class="row team_preview">
		@{
			var mems = Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("featuredTeamMembers");
		}
		@foreach(var tm in mems) {
			<div class="col-xs-12 col-sm-4">
				<a href="@tm.Url()">
					@{ var tmImg = tm.GetPropertyValue<IPublishedContent>("homeImage") == null ? "" : tm.GetPropertyValue<IPublishedContent>("homeImage").Url(); }
					<img src="@tmImg" class="img-responsive" alt="" />
					<figcaption>
						<span class="teammembername">@tm.GetPropertyValue("homeFirst") <span>@tm.GetPropertyValue("homeLast")</span></span>
						<p>@tm.GetPropertyValue("homeBlurb")</p>
					</figcaption>
				</a>
			</div>
		}
		</div>
	</div>


</div>

ShareHouseTheatre/Views/Home_Temp.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

<!DOCTYPE html>
<html lang="en">
<head>
	@Html.Partial("pageMaster/head")
	<link href="/css/temp.css" rel="stylesheet">
</head>

<body>
    <div id="homeTemp">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 banner_text">
					<svg viewBox="0 0 500 250">
						<!-- Symbol-->
						<symbol id="s-text">
						<text text-anchor="middle" x="50%" y="20%" dy=".35em">Share House</text>
						<text text-anchor="middle" x="50%" y="48%" dy=".35em">Theatre</text>
						</symbol>
						<!-- Duplicate symbols-->
						<use class="text" xlink:href="#s-text"></use>
						<use class="text" xlink:href="#s-text"></use>
						<use class="text" xlink:href="#s-text"></use>
						<use class="text" xlink:href="#s-text"></use>
						<use class="text" xlink:href="#s-text"></use>
					</svg>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<div class="we_are">
						<p>We are</p>
						<ul>
							<li>Indie</li>
							<li>Collaborative</li>
							<li>Inclusive</li>
							<li>Theatre</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

ShareHouseTheatre/Views/MacroPartials/uBlogsy/uBlogsyMacroShowSomeLove.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="N9X53FAAM6WU6">
        <input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online.">
        <img alt="" border="0" src="https://www.paypalobjects.com/en_AU/i/scr/pixel.gif" width="1" height="1">
    </form>
}	

ShareHouseTheatre/Views/PageMaster.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
<!DOCTYPE html>
<html lang="en">
<head>
	@Html.Partial("pageMaster/head")

	@RenderSection("headScripts", false)
</head>

<body>
	@Html.Partial("pageMaster/nav")

	@RenderBody()

	@Html.Partial("pageMaster/footer")

	@RenderSection("scripts", false)
</body>
</html>

ShareHouseTheatre/Views/Partials/Contact/ContactForm.cshtml
@model ShareHouseTheatre.Models.ContactModel
@using system;

<div id="loading" style="display:none; padding: 15px 0; text-align: center;">
	<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
	<span class="sr-only">Loading...</span>
</div>
@using(Ajax.BeginForm("Contact", "ContactSurface", new AjaxOptions { HttpMethod = "POST", LoadingElementId = "loading", UpdateTargetId = "update" })) {
<div id="update">
	<div>
		@Html.TextBoxFor(m=>m.Name, new { placeholder="Name *" })
	</div>
	<div>
		@Html.TextBoxFor(m=>m.RequiredToPost, new { placeholder="Required last name", className="req", id=Guid.NewGuid(), tabindex = "-1", autocomplete = "false", style="display: none;" })
	</div>
	<div>
		@Html.TextBoxFor(m => m.Email, new { placeholder = "Email *" })
	</div>
	<div>
		@Html.TextBoxFor(m => m.Website, new { placeholder = "Website" })
	</div>
	<div>
		@Html.HiddenFor(m=>m.Required)
		@{ 
			//Create super basic encryption
			char[] _base = DateTime.Now.ToString("yyyyMMddHHmmss").ToCharArray();
			char[] salt = "Milkman Matty".ToCharArray();
			char[] enc = new char[_base.Length];
			for(int i = 0; i < _base.Length; i++) {
				enc[i] = (char) ( _base[i] + salt[i%salt.Length] );
			}
		}
		@Html.HiddenFor(m=>m.T, new { Value=new string(enc) })
	</div>
	<div>
		@Html.TextAreaFor(m => m.Message, new { placeholder = "Message *" })
		<p class="badge-important small">Do not post websites/URLs in the message!</p>
	</div>
	<input type="submit" class="round-btn" name="Submit" value="Submit" />
</div>
}

ShareHouseTheatre/Views/Partials/Contact/ContactFormError.cshtml
@{ var error = ViewBag.error.ToString(); }
@if(String.IsNullOrEmpty(error)) {
<p class="error">An error occured and you message could not be delivered.</p>
} else {
<p class="error">An error occured and you message could not be delivered. @error</p>
}

ShareHouseTheatre/Views/Partials/Contact/ContactFormSuccess.cshtml
<p class="success">Success! Your message has been sent to Share House Theatre.</p>

ShareHouseTheatre/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

ShareHouseTheatre/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

ShareHouseTheatre/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

ShareHouseTheatre/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}